//REDUCER TYPES
export const SET_USERS = "SET_USERS";
export const SET_USERS_NUMBER = "SET_USERS_NUMBER";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_USER_REPOS = "SET_USER_REPOS";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
